### ISSUE TITLE
How to enable php module?

### ISSUE THREAD

**Issue by Richi2293** [chriszarate/docker-compose-wordpress#13]
Hi,

I'm trying to enable the exif module of php but it would seem that I'm missing something.

- created new file 'phpimage.ini'
- edit docker.compose file adding this entry in the volume (serives/wordpress):
- ./phpimage.ini:/usr/local/etc/php/conf.d/phpimage.ini
- restart of docker

Maybe it is not installed in the system? I tried but I encounter many difficulties.

Thanks

**Comment by modelm** [comment]
I think you have to create your own image and add your package install to the Dockerfile using `docker-php-ext-install`: https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions
