### ISSUE TITLE
Can't wp db export: Permission Denied

### ISSUE THREAD

**Issue by MikeiLL** [chriszarate/docker-compose-wordpress#21]
Not sure if you're still maintaining the (awesome) repo.

This seems like a limitation:

```
docker-compose run --rm wp-cli wp db export
Creating my_project_wp-cli_run ... done
mysqldump: Can't create/write to file 'wordpress-2021-09-08-1296a45.sql' (Errcode: 13 "Permission denied")
```

Tried running with `sudo`. No success.

**Comment by chriszarate** [comment]
The current directory gets mapped read-only into the container:

https://github.com/chriszarate/docker-compose-wordpress/blob/master/docker-compose.yml#L19

Without making any changes, you can target `stdout` by passing `-` as the file path (see [WP-CLI docs](https://developer.wordpress.org/cli/commands/db/export/)) and then redirect the output locally to a file:

```sh
docker-compose run --rm wp-cli wp db export - > dump.sql
```

Alternatively, remove the `:ro` flag from the volume mount. Or map a different volume and point the dump there.

**Comment by MikeiLL** [comment]
Thanks much, Chris.
